apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloghub-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloghub-server
  template:
    metadata:
      labels:
        app: bloghub-server
    spec:
      containers:
      - image: saberhamidi/bloghub-server:1.0
        name: server
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
